// var age = 123;
// console.log(typeof age);
// age = age.toString();
// console.log(typeof age);
// age = String(age);
// console.log(typeof age)
// age = Number(age);
// console.log(age);
// age = undefined;
// age = Number(age);
// console.log(age);
// var d = 20;
// //var result = d++ + ++d +d; //20+22+22
// d = d++;
// console.log("d="+d);
// var result = 5 && 6;
// console.log(result);
// var result = null && 0;
// console.log(result);

// var result = 0 || 123;
// console.log(result);
// var  ab = '2'.charCodeAt();
var a =[];
a = Boolean(a);
console.log(a);
